sudo: required
dist: trusty
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"

before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common
  - psql -c 'create database hll_regress;' -U postgres

  
script:
  - make && sudo make install
  - psql -c "create extension hll" hll_regress -U postgres
  - make -C regress
