sudo: required
dist: trusty
language: c
matrix:
  fast_finish: true
  include:
    - env: PGVERSION=9.4
    - env: PGVERSION=9.5
    - env: PGVERSION=9.6
    - env: PGVERSION=10
    - env: PGVERSION=11
    - env: PGVERSION=11
before_install:
  - git clone -b v0.7.5 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - setup_apt
  - nuke_pg
install:
  - install_uncrustify
  - install_pg
before_script:
  - config_and_start_cluster
script: pg_travis_test
